### ISSUE TITLE
Suggestion: Generate Zip of Chrome Extension using Rules of JS/CSS

### ISSUE THREAD

**Issue by KevynTD** [tenRabbits/user-js-css-docs#2]
Your extension is already amazing, thank you!

I recently thought about creating an chrome extension that does exactly what the code I run in your extension does.

I know it might go a little beyond the scope of the project, but it's not that far from it!
**What if** there was an option where I click to generate an extension, a new popup appears with the list of previously created JS/CSS rules. I select the ones I want in my extension, some other options like name, version, icon, and it allows me to export an entire extension inside a zip file (it could be using a frontend lib, like [jszip](https://www.npmjs.com/package/jszip), which is very easy to use and create folders and files inside a zip file).

This would make it much easier to create extensions that modify pages. Of course, it doesn't cover all types of extensions, like those that mess with the drop-down menu, or with a mini HTML screen in the icon, but it would make extensions that make simple modifications easier.

Since the scope of possible extensions is quite limited, it doesn't seem that difficult to generate a more standardized manifest or even the URL options (but I'm not an extension expert, it's been a long time since I made one).

What do you think?

**Comment by tenRabbits** [comment]
Hello, @KevynTD , thanks for the message!

I understand, but this is really beyond the scope of my extension's goal. I don't think this will be a popular feature, and it will be necessary to support it.
