### ISSUE TITLE
FR: Save starting code as boilerplate template and use saved boilerplate template when creating a new rule.

### ISSUE THREAD

**Issue by jerrywoo96** [tenRabbits/user-js-css-docs#3]
Hello, thanks for this amazing extension. I would like to propose a feature request as to help make life easier when creating a new rule.

My problem:
I have to write the same boilerplate code and re-enable my preferred settings by myself every time i create a new rule.

Solution:
I would like to save a boilerplate code as a template, including js settings, css settings and modules enabled.
I would then like my boilerplate code to be pre-filled and settings restored in every time i create a new rule.

**Comment by tenRabbits** [comment]
Hi, thanks for the message and sorry for the late reply!

I've been thinking about this for a while now, I've added it to my backlog.
